/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.cine.ui;

import java.util.ArrayList;
import java.util.List;
import poo.cine.Funcion;
import poo.cine.Pelicula;
import poo.cine.dao.PeliculasDaoImpl;

/**
 *
 * @author roberto
 */
public class PantallaListadoPeliculas extends javax.swing.JPanel {

    private List<Pelicula> peliculas = new ArrayList<>();
    
    /**
     * Creates new form PantallaListadoPeliculas
     */
    public PantallaListadoPeliculas() {
        PeliculasDaoImpl peliculasDao = new PeliculasDaoImpl();
        peliculas.addAll(peliculasDao.obtenerTodos());
        initComponents();
        selPelicula.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selPelicula = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        selFuncion = new javax.swing.JComboBox<>();

        selPelicula.setModel(new javax.swing.DefaultComboBoxModel(peliculas.toArray()));
        selPelicula.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selPeliculaItemStateChanged(evt);
            }
        });

        jLabel1.setText("Pelicula:");
        jLabel1.setToolTipText("");

        jLabel2.setText("Funcion:");

        selFuncion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selFuncion.setSelectedIndex(-1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(selPelicula, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(selFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(189, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selPeliculaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selPeliculaItemStateChanged
        // TODO add your handling code here:
        updateSelFunciones((Pelicula) selPelicula.getSelectedItem());
    }//GEN-LAST:event_selPeliculaItemStateChanged

    public void updateSelFunciones(Pelicula pelicula) {
        if (pelicula != null) {
            List<Funcion> funciones = pelicula.getFunciones();
            selFuncion.setModel(new javax.swing.DefaultComboBoxModel(funciones.toArray()));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> selFuncion;
    private javax.swing.JComboBox<String> selPelicula;
    // End of variables declaration//GEN-END:variables
}
