/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.cine.ui;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultListModel;
import poo.cine.Funcion;
import poo.cine.Pelicula;
import poo.cine.dao.PeliculasDaoImpl;

/**
 *
 * @author roberto
 */
public class PantallaListadoPeliculas extends javax.swing.JPanel {

    private List<Pelicula> peliculas = new ArrayList<>();
    
    /**
     * Creates new form PantallaListadoPeliculas
     */
    public PantallaListadoPeliculas() {
        PeliculasDaoImpl peliculasDao = new PeliculasDaoImpl();
        peliculas.addAll(peliculasDao.obtenerTodos());
        initComponents();
        selPelicula.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selPelicula = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        funcionesList = new javax.swing.JList<>();

        selPelicula.setModel(new javax.swing.DefaultComboBoxModel(peliculas.toArray()));
        selPelicula.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selPeliculaItemStateChanged(evt);
            }
        });

        jLabel1.setText("Pelicula:");
        jLabel1.setToolTipText("");

        jLabel2.setText("Funciones:");

        funcionesList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        funcionesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(funcionesList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(14, 14, 14)
                            .addComponent(selPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jLabel2.getAccessibleContext().setAccessibleName("Funciones");
    }// </editor-fold>//GEN-END:initComponents

    private void selPeliculaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selPeliculaItemStateChanged
        updateFuncionesList((Pelicula) selPelicula.getSelectedItem());
    }//GEN-LAST:event_selPeliculaItemStateChanged

    public void updateFuncionesList(Pelicula pelicula) {
        if (pelicula != null) {
            DefaultListModel listModel = new DefaultListModel();

            List<Funcion> funciones = pelicula.getFunciones();
            Iterator<Funcion> it = funciones.iterator();
            while (it.hasNext()) {
                Funcion funcion = it.next();
                listModel.addElement(funcion.toString());
            }

            funcionesList.setModel(listModel);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> funcionesList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> selPelicula;
    // End of variables declaration//GEN-END:variables
}
